[package]
name = "schnorr_protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"  # For secure random number generation
sha2 = "0.10" # For SHA-256 hashing
num-bigint = "0.4" # For large integer calculations